# Project Information
#projectName: "California Favorability Data"
#projectId: "POLAACOKS2024"


# Database Connection
serverName: 50.19.30.69
databaseName: POLAACOKS2024
connectionCredentialsName: prime

# SQLAlchemy & ODBC
sqlAlchemyDialect: mssql+pyodbc
sqlServerDriverName: SQL+Server+Native+Client+10.0

# Credentials [prime]
dbUsername:
dbPassword:

# Paths
#metadataOutputPath:
#variableDefinitionsPath:
#tableDefinitionsPath:
#sourceDirectory:
#configDirectory:
geo_file_path: C:\Projects\db_data_retrieval\datasets\POLAACOKS2024\dp_POLAACOKS2024\preprocessed_data
geo_file: C:\Projects\db_data_retrieval\datasets\POLAACOKS2024\dp_POLAACOKS2024\preprocessed_data\geo_identifiers.csv
data_folder: C:\Projects\db_data_retrieval\datasets\POLAACOKS2024\dp_POLAACOKS2024\preprocessed_data



###############################################################################
# geo level information
################################################################################

geoLevelInformation:

# THE FIRST GEO LEVEL SUCH AS UNITED STATES, WORLD, CANADA, UK, EUROPE, ETC
# MUST HAVE SHORTER FIPS CODE LENGTH THAN ANY OTHER GEO NESTED UNDER IT

    -
        - SL040    # Geo_level
        - STATE   # Geo_level_name
        - "2"    # FIPS_length
        - "2"    # PARTIAL_FIPS_length
        - "0"    # Indent
    -
        - SL610    # Geo_level
        - SLDU   # Geo_level_name
        - "5"    # FIPS_length
        - "3"    # PARTIAL_FIPS_length
        - "1"    # Indent
    -
        - SL620    # Geo_level
        - SLDL   # Geo_level_name
        - "5"    # FIPS_length
        - "3"    # PARTIAL_FIPS_length
        - "1"    # Indent
    -
        - SL050    # Geo_level
        - COUNTY   # Geo_level_name
        - "5"    # FIPS_length
        - "3"    # PARTIAL_FIPS_length
        - "1"    # Indent
...
