# Project Information
#projectName: "California Favorability Data"
#projectId: "LAKEPRIM2024"


# Database Connection
serverName: 50.19.30.69
databaseName: LAKEPRIM2024
connectionCredentialsName: prime

# SQLAlchemy & ODBC
sqlAlchemyDialect: mssql+pyodbc
sqlServerDriverName: SQL+Server+Native+Client+10.0

# Credentials [prime]
dbUsername: sewebsite3
dbPassword: granted128

# Paths
#metadataOutputPath:
#variableDefinitionsPath:
#tableDefinitionsPath:
#sourceDirectory:
#configDirectory:
geo_file_path: C:\Projects\db_data_retrieval\datasets\LAKEPRIM2024\dp_LAKEPRIM2024\preprocessed_data
geo_file: C:\Projects\db_data_retrieval\datasets\LAKEPRIM2024\dp_LAKEPRIM2024\preprocessed_data\geo_identifiers.csv
data_folder: C:\Projects\db_data_retrieval\datasets\LAKEPRIM2024\dp_LAKEPRIM2024\preprocessed_data



###############################################################################
# geo level information
################################################################################

geoLevelInformation:

# THE FIRST GEO LEVEL SUCH AS UNITED STATES, WORLD, CANADA, UK, EUROPE, ETC
# MUST HAVE SHORTER FIPS CODE LENGTH THAN ANY OTHER GEO NESTED UNDER IT

    -
        - SL010    # Geo_level
        - Nation   # Geo_level_name
        - "0"    # FIPS_length
        - "0"    # PARTIAL_FIPS_length
        - "0"    # Indent
    -
        - SL040    # Geo_level
        - State   # Geo_level_name
        - "2"    # FIPS_length
        - "2"    # PARTIAL_FIPS_length
        - "1"    # Indent
    -
        - SL500    # Geo_level
        - CD118   # Geo_level_name
        - "4"    # FIPS_length
        - "2"    # PARTIAL_FIPS_length
        - "2"    # Indent
    -
        - SL610    # Geo_level
        - SLDU   # Geo_level_name
        - "5"    # FIPS_length
        - "3"    # PARTIAL_FIPS_length
        - "2"    # Indent
    -
        - SL620    # Geo_level
        - SLDL   # Geo_level_name
        - "5"    # FIPS_length
        - "3"    # PARTIAL_FIPS_length
        - "2"    # Indent
    -
        - SL960    # Geo_level
        - SMM   # Geo_level_name
        - "5"    # FIPS_length
        - "3"    # PARTIAL_FIPS_length
        - "2"    # Indent
    -
        - SL961   # Geo_level
        - SMM  # Geo_level_name
        - "5"   # FIPS_length
        - "3"  # PARTIAL_FIPS_length
        - "2"  # Indent
    -
        - SL050    # Geo_level
        - County   # Geo_level_name
        - "5"    # FIPS_length
        - "3"    # PARTIAL_FIPS_length
        - "2"    # Indent
    -
        - SL900    # Geo_level
        - Precinct 2020 a  # Geo_level_name
        - "14"    # FIPS_length
        - "9"    # PARTIAL_FIPS_length
        - "3"    # Indent
    -
        - SL901    # Geo_level
        - Precinct 2022 b
        - "11"
        - "6"
        - "3"
    -
        - SL902    # Geo_level
        - Precinct   # Geo_level_name
        - "7"    # FIPS_length
        - "5"    # PARTIAL_FIPS_length
        - "2"    # Indent
    -
        - SL140    # Geo_level
        - Census Tract   # Geo_level_name
        - "11"    # FIPS_length
        - "6"    # PARTIAL_FIPS_length
        - "3"    # Indent
...